
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: skupos_bucket_extract
    description: "table filled from transactions bucket"
    columns:
      - name: transaction_set_id
        description: "unique identifier of the transaction"
      - name: store_id
        description: "store id for the transaction" 
      